source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NNIntegerArray_Example', :exclusive => true do
  pod "NNIntegerArray", :path => "../"
end

target 'NNIntegerArray_Tests', :exclusive => true do
  pod "NNIntegerArray", :path => "../"

  
end
